services:
  inventory:
    image: ghcr.io/williamjacksn/inventory
    init: true
    environment:
      DSN: postgres://postgres:postgres@postgres/postgres
      OPENID_CLIENT_ID: (set in docker-compose.override.yaml)
      OPENID_CLIENT_SECRET: (set in docker-compose.override.yaml)
      OPENID_DISCOVERY_DOCUMENT: (set in docker-compose.override.yaml)

  postgres:
    image: postgres:11.11-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/11
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
